// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvfsoziizefhyopipbuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2ZnNvemlpemVmaHlvcGlwYnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDczODksImV4cCI6MjA1OTkyMzM4OX0.SDJZqW95SVERoRiLcb8xCblusQoGP1KWTV4j1tBJRcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);